### ISSUE TITLE
Update URLs everywhere

### ISSUE THREAD

**Issue by cowboy** [vlandham/js_data#14]
to http://learnjsdata.com/

**Comment by vlandham** [comment]
Thanks @cowboy - just to clarify, are you suggesting converting all relative links to absolute ones - or just the spots where I linked to the old repo?

**Comment by cowboy** [comment]
Not sure. I clicked a few links and they went to http://vallandingham.me/js_data/ and I saw that was the repo's URL. I just figured you'd want to update anything you could to the .com address.

**Comment by iros** [comment]
@vlandham I think he means this:

![image](https://cloud.githubusercontent.com/assets/18690/6669235/32e8dcaa-cbce-11e4-8baa-2d9d279a3b2f.png)

**Comment by iros** [comment]
And this:

![image](https://cloud.githubusercontent.com/assets/18690/6669243/3e58b27c-cbce-11e4-905b-c534764dc335.png)

**Comment by vlandham** [comment]
sounds good. will put in hot-fix
