### ISSUE TITLE
Add is.js for validations in "Checking Data Assumptions" task

### ISSUE THREAD

**Issue by glena** [vlandham/js_data#23]
Hi, 

I found http://arasatasaygin.github.io/is.js very useful for the kind of validations that you state on the  "Checking Data Assumptions" task.

What do you think?

**Comment by kgryte** [comment]
Or if you prefer a more modular approach, see [validate.io](https://github.com/validate-io).

**Comment by glena** [comment]
this is a nice repo too.

**Comment by vlandham** [comment]
Thanks @glena and @kgryte  - great suggestions. I'll plan on putting both these links in the 'see also' if that is ok. we are also planning a 'tools' section - with "where to go next" - but that hasn't been created yet.

**Comment by kgryte** [comment]
+1.

**Comment by glena** [comment]
@vlandham yesterday I translated this page to spanish so let me know to update this one too :)

**Comment by vlandham** [comment]
haha. ok! thank you. and to complicate things - we just got a new
contributed page: http://learnjsdata.com/combine_data.html

**Comment by glena** [comment]
haha no prob. 

In this cases can you keep us up to date updating the issue #17 "Add Spanish translation" and or creating an issue in this fork https://github.com/davo/js_data?

**Comment by iros** [comment]
Done @glena! New issue made.

**Comment by glena** [comment]
Great :)
thanks

**Comment by vlandham** [comment]
sorry for the delay on this. 
adding both now!
