### ISSUE TITLE
help for beginner on d3.csv display

### ISSUE THREAD

**Issue by steventsimpson** [vlandham/js_data#27]
Hi, I was excited by this d3 for data wrangling idea, because I'm wanting to combine R's `dplyr` with data viz. But feel like hand coding the data feels a bit silly when there's reams of it.  

I know that this is probably not what your help is for, but I'm trying to follow your tutorial on loading data with d3.csv and I can get the console log to print to the html page. ANd I 'm not sure if it supposed to or not.  I'm getting the feeling that this tutorial is not meant for me, but since I'm an avid user of dplyr your page makes it sounds like this is something I should be able to do or want to do. It would be so helpful if your github account actually contained the d3 code in the finish html file. 

Other d3 tutorials have examples that just display to the web out of the box, so I'm assuming the console.log is supposed to log to the html, not the console itself. thanks

**Comment by vlandham** [comment]
Hi @steventroysimpson - sorry you are having some issues with the data loading. 

The instructions might be a bit confusing. `console.log` is supposed to print out to the console - which is a sort of debugging screen. On chrome, if you click the View drop down menu - then Developer and then JavaScript Console, then it should open the console and you should see the output of the console.log's.

You should actually be able to see them in the tutorial itself (as the tutorial is running all that code in the browser). So if you open the console on the 'reading in data' section of the tutorial, you should see something like this:

![screen shot 2015-04-10 at 8 04 54 pm](https://cloud.githubusercontent.com/assets/9369/7099996/f69108ba-dfbc-11e4-8c0f-20467945436d.png)

so those 'objects' are what the console.log statements are printing.

Hope this helps - if not, let me know how to get this going better for you!

**Comment by timelyportfolio** [comment]
_Looks like @vlandham was responding at the same time as me_

Have you tried Developer Tools (Ctrl + Shift +I) in Chrome?  That is how you will see the console and the output.  This would be equivalent to a console in `R`.

I love R and JavaScript and very often combine the two.  My opinion, but I think this question is definitely not in the right place.  Before proceeding with this tutorial, I would recommend some beginning `HTML` and `JS`.  Here is a great [list of freely available books on JavaScript](https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#javascript).

**Comment by steventsimpson** [comment]
Thanks, yes. I've done js (minimally I guess, working towards angular and opencpu combo that makes me less dependent of shiny) but was expecting d3 something else for some reason. I eventually realized that in other folders of the github repo the public folder had the files and could see output in the developer tools. 

In the github version I downloaded I found some JavaScript dependencies had a few typos. Like d3 or lodash src had / before lib or custom.css was in a different folder, I guess because I was looking in public. This kept the pages from loading d3. 

Also when I copied and pasted the join functions  in console they didn't produce the same output your page showed. It very well could be my incorrect usage but in case it's not I hope I've communicated it with the right spirit of gratefulness for your work. 

Are you really the timelyportfio blogger? If so, I'm a big fan. Reading those posts have convinced me to move beyond R. 

Thanks !

~ Steve

Sent via telepathy

**Comment by timelyportfolio** [comment]
Yep, I'm the world famous (not hardly) timelyportfolio.  I'm guessing @vlandham welcomes pull requests or issues regarding typos.  I would love to see a side-by-side `dpylr`/`js_data` how-to if you get really motivated.  I don't think I have the time, but I could help edit, test, proofread.

Also, if you have not seen it, you might be interested in this angular+ace+opencpu http://rcharts.io/viewer/live/.

**Comment by vlandham** [comment]
thanks to @timelyportfolio and sorry again to @steventroysimpson that you were having problems with the repo. We went through a few iterations in how the site was built - and so we might have some old code in need of removal. 

Really glad you still found this somewhat useful, and my apologies again that you ran into difficulties.

**Comment by ndarville** [comment]
I recommend that you ditch the plain `console.log()` (which is useless for dictionaries, objects, and arrays, as you point out) and replace it with `console.log(JSON.stringify(myData, null, 2));`

This prints your data in a way that is much more understandable, because figuring out how D3 processes your data is obviously crucial to the understanding.

**Comment by steventsimpson** [comment]
Wisdom and thanks. It's good stuff. 

~ Steve

Sent via telepathy

**Comment by vlandham** [comment]
Thanks @ndarville for the suggestion. Right now i have both in places. I sort of like the succinctness of plain console.log() and that you can expand the output inline. But you are right, that it isn't immediately useful with more complex types. 

For now, I think I'll keep the mixture - but start to think of a section for calling these and other functions for outputting debugging and other messages out.

Thanks!

**Comment by vlandham** [comment]
i've deleted the old src files from the old build process - so now everything should be in sync. The code should all compile and run.

**Comment by ndarville** [comment]
You’ll probably want to just get the first one, or two, elements from an
array, when using stringify(), so you don’t get a full console of it—unless
you want to inspect all the values, ofc.

On 13 April 2015 at 00:12, Jim Vallandingham notifications@github.com
wrote:

> Thanks @ndarville https://github.com/ndarville for the suggestion.
> Right now i have both in places. I sort of like the succinctness of plain
> console.log() and that you can expand the output inline. But you are right,
> that it isn't immediately useful with more complex types.
> 
> For now, I think I'll keep the mixture - but start to think of a section
> for calling these and other functions for outputting debugging and other
> messages out.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vlandham/js_data/issues/27#issuecomment-92142270.

## 

twitter.com/pessimism
github.com/ndarville
ndarville.com

8ACC 17A5 EA8B BC19 https://keybase.io/ndarville
