### ISSUE TITLE
Use only lodash to trim object keys and values

### ISSUE THREAD

**Issue by yonester** [vlandham/js_data#32]
In the [Stripping Whitespace](http://learnjsdata.com/strings.html#stripping-whitespace) section, both d3 and lodash are used to do the string trimming. It might be a bit cleaner to just use lodash and avoid the temporary variable as a bonus.

```js
d3.csv("data/cities_spaced.csv", function(data) {
  var clean = data.map(function(d) {
    return _.reduce(d, function(acc, v, k) {
      return acc[_.trim(k)] = _.trim(v), acc;
    }, {});
  });

  console.log(clean);
});
```

Alternatively, you might consider breaking this up for further clarity.

```js
function trimObject(o) {
  return _.reduce(o, function(acc, v, k) {
    return acc[_.trim(k)] = _.trim(v), acc;
  }, {});
}

d3.csv("data/cities_spaced.csv", function(data) {
  var clean = data.map(trimObject);
  console.log(clean);
});
```

It would probably be helpful to mention that lodash `_.reduce` is similar to the Javascript built-in `reduce`, except it works both on arrays _and_ objects. When we use it on an object our function is given a value and key with each iteration rather than an array's value and index.

**Comment by yonester** [comment]
Let me know if you'd like me to create a PR. I just wanted to get your take on it first.

**Comment by vlandham** [comment]
interesting! thank you for the input. 

I really like your idea of splitting this into two separate functions. That really makes it read better.

I guess my only hesitation about `_.reduce` is the more complex API call. 
Perhaps its work showing both methods? 

start with the `d3.nest()` approach then introduce `_.reduce()`?

in both cases, i like your opinion to split the function out.

**Comment by yonester** [comment]
That's a fair point. If you want the code to be more instructive and easier to read, you can also be very explicit with the intermediate variables.

``` js
function trimObject(o) {
  return Object.keys(o).reduce(function(result, key) {
    var keyTrimmed = _.trim(key),
        valTrimmed = _.trim(o[key]);
    result[keyTrimmed] = valTrimmed;
    return result;
  }, {});
}
```

I'm using `Object.keys` instead of `d3.keys` because it's supported in ES5, so it's quite safe to use anywhere. I tend to prefer built-in methods where it makes sense.

**Comment by yonester** [comment]
In any case, since this is really just a suggestion, rather than an "issue", I'm going to close this item. The website you create is a really great educational tool. I'm happy to contribute if you need a hand. Cheers.

**Comment by vlandham** [comment]
well, i think these are great ideas!

if you want to contribute this as an additional option - i'd love to add it.
