### ISSUE TITLE
csv function behaves differently in d3 v5

### ISSUE THREAD

**Issue by noobling** [vlandham/js_data#40]
This one confused me a bit so in case this also confuses other people. In d3 v5 if you copy the `d3.csv` code here http://learnjsdata.com/read_data.html it won't work because the callback doesn't get passed all the csv data, but a line of csv data. This is because of the changes here https://github.com/d3/d3/blob/master/CHANGES.md in short to get the same result you have to use promises e.g. `d3.csv('file.csv').then(cbFunction)`

I used this guide as an intro to d3 so I wasn't aware about the varying versions, so maybe it would be helpful to newcomers to note this difference down?

**Comment by vlandham** [comment]
Very good point! The v5 recently came out - and you are completely right, this guide should be updated to address the changes to the API to use Promises. 

Thanks for calling this out. I will look to incorporate your suggestions into this guide. 

Thanks very much again!

**Comment by noobling** [comment]
No problem let me know if you need any help

**Comment by erinbrown** [comment]
I was aware of v5 changes when started working through the tutorial, so I made some updates. These can be found in PR https://github.com/vlandham/js_data/pull/42. 

I hope this helps!

**Comment by vlandham** [comment]
Awesome and amazing! thanks! I need to figure out how to update the site with these!

**Comment by vlandham** [comment]
I believe this is now functional. thank you and sorry for the long delay.
